### PR TITLE
I18n: various fixes

### LINKED ISSUE #35: `Yoast SEO` shouldn't be translatable
Found one occurrence in the new strings available on glotpress:

`vendor/yoast/whip/src/messages/Whip_UpgradePhpMessage.php:32`
...
Hey, we've noticed that you're running an outdated version of PHP. PHP is the programming language that WordPress and Yoast SEO are built on ...

### PR DESCRIPTION
**Pull request by jrfnl**
### I18n: fix incorrect text-domain

The text-domain for WordPress itself is `default`, not `wordpress`.

### I18n: add missing translators comments

Includes minor efficiency fix for `sprintf()`: when using numbered replacements, you can use the same replacement twice, so no need to have `'</a>'` twice in the replacement list.

### I18n: Make the text slightly more plugin agnostic

AFAIK WHIP is intended to also be usable by other (non-Yoast) plugins/themes.
There were currently two phrases which made this awkward.

This PR changes those.

For the first phrase, I've chosen to change `WordPress and Yoast SEO` to `WordPress and all it's plugins and themes`. This incidentally fixes issue #35. /cc @afercia 
If it is preferred that `Yoast SEO` not be removed, I would suggest the following:
* Move the name out of the text string and put it back in using `sprintf()`.
* Make the name filterable to allow other plugins to pass in their plugin name.
    - Potentially, it could even be turned into an array which could be passed into the string using `implode()` to allow for a number of plugins to be mentioned.

For the second phrase, just changing the `our` in `vetted by our Yoast support team` to `the` improves the re-usability.

Fixes #35

### CODE REVIEW

File: src/messages/Whip_UpgradePhpMessage.php [hunk 1]
```diff
@@ -35,11 +35,12 @@ public function body() {
 		$message = array();
 
 		$message[] = Whip_MessageFormatter::strongParagraph( __( 'Your site could be faster and more secure with a newer PHP version.', $textdomain ) ) . '<br />';
-		$message[] = Whip_MessageFormatter::paragraph( __( 'Hey, we\'ve noticed that you\'re running an outdated version of PHP. PHP is the programming language that WordPress and Yoast SEO are built on. The version that is currently used for your site is no longer supported. Newer versions of PHP are both faster and more secure. In fact, your version of PHP no longer receives security updates, which is why we\'re sending you to this notice.', $textdomain ) );
+		$message[] = Whip_MessageFormatter::paragraph( __( 'Hey, we\'ve noticed that you\'re running an outdated version of PHP. PHP is the programming language that WordPress and all it\'s plugins and themes are built on. The version that is currently used for your site is no longer supported. Newer versions of PHP are both faster and more secure. In fact, your version of PHP no longer receives security updates, which is why we\'re sending you to this notice.', $textdomain ) );
```
Comment (jdevalk) [inline src/messages/Whip_UpgradePhpMessage.php]: its, not it's

Comment (jrfnl) [reply src/messages/Whip_UpgradePhpMessage.php]: Thanks for catching that!
